Sprint 12 - First Commit - Trying to realise ImagesListService(get-request)
DanteIT94/pinterestClone pull request #6
Opened 2023-05-17 15:53 UTC by DanteIT94

2023-05-24 19:09 UTC, ABashkirova requested changes
К сожалению работу проверить не удалось, после авторизации дальше не пускает. 

скорее всего проблема с моделью профиля: поле lastName может приходить опциональным. Это можно проверить, изменив настройки профиля - сохранить все поля пустые, например: 

<img width="751" alt="Снимок экрана 2023-05-09 в 21 07 21" src="https://github.com/DanteIT94/pinterestClone/assets/20269264/d9911b83-809d-45a5-b794-e5052bd211d3">

Без исправления этой ошибки я не смогу проверить твою работу

2023-05-24 19:09 UTC, ABashkirova commented on pinterestClone.xcodeproj/project.pbxproj
> +		92F5904E2A12CAE8002727E3 /* KeyChainManager(NEED TO ADD).swift in Sources */ = {isa = PBXBuildFile; fileRef = 92F5904D2A12CAE8002727E3 /* KeyChainManager(NEED TO ADD).swift */; };
Подскажи, в чем потребность указывать в скобочках такие штуки как `(NEED TO ADD)`, `JSON` и так далее?

я не видела такой практики в нейминге, и в целом стараются избегать в названиях такие символы и смешение стилей (капс, camelCase)

2023-05-24 19:09 UTC, ABashkirova commented on pinterestClone/ImagesListFolder/ImagesListService.swift
> +                return
return тут не нужен, выход из тела кложуры будет сделан естественным образом по завершению всех инструкций

2023-05-24 19:09 UTC, ABashkirova commented on pinterestClone/ImagesListFolder/ImagesListService.swift
> +
давай договоримся не оставлять больше одной разделительной пустой строки

2023-05-24 19:09 UTC, ABashkirova commented on pinterestClone/ImagesListFolder/ImagesListService.swift
> +        let dataTask = urlSession.objectTask(for: request) {[weak self] (result: Result<[PhotoResult],Error>) in
фигурные скобки, перечисления сопровождаются пробелами, чтобы код не слипался 
```suggestion
        let dataTask = urlSession.objectTask(for: request) { [weak self] (result: Result<[PhotoResult], Error>) in
```

2023-05-24 19:09 UTC, ABashkirova commented on pinterestClone/ImagesListFolder/ImagesListViewController.swift
> +                guard let self else {return}
```suggestion
                guard let self else { return }
```

2023-05-24 19:09 UTC, ABashkirova commented on pinterestClone/ImagesListFolder/ImagesListViewController.swift
> +                self.showAlertViewController()
очень странно, что в блоке успеха ты переводишь на главную очередь, а в ошибке нет. Выглядит как неконсистенность: надо выяснить нужно ли обернуть в DispatchQueue.main.async код из ошибки, или наоборот убрать обертку в успехе.

2023-05-24 19:09 UTC, ABashkirova commented on pinterestClone/ImagesListFolder/ImagesListViewController.swift
> +    }
это вычисляемое свойство, при обращении к нему ты будешь каждый раз создавать новый форматтер. Это не оптимально, и в чеклисте требовалось создавать форматтер всего раз. Связанно это с достаточно большими затратами на создание и настройку форматтера (https://sarunw.com/posts/how-expensive-is-dateformatter), а обращение к этому свойству при формировании ячейки, вполне может вызывать тормоза на слабых девайсах.

2023-05-24 19:09 UTC, ABashkirova commented on pinterestClone/UserProfileFolder/ProfileViewController.swift
> +        tokenStorage.keychainWrapper.removeObject(forKey: "token")
.keychainWrapper - это зависимость стораджа, должна быть закрыта приватным модификатором. Стучаться через нее чтобы удалить свойство - архитектурная ошибка (не соблюдение принципов сокрытия реализации).

2023-05-25 11:07 UTC, DanteIT94 commented on pinterestClone.xcodeproj/project.pbxproj
> +		92F5904E2A12CAE8002727E3 /* KeyChainManager(NEED TO ADD).swift in Sources */ = {isa = PBXBuildFile; fileRef = 92F5904D2A12CAE8002727E3 /* KeyChainManager(NEED TO ADD).swift */; };
Ставил себе зрительные напоминания (чтобы не забыть вернуться к ним при оптимизации / рефакторинг кода)

2023-05-25 12:32 UTC, DanteIT94 commented on pinterestClone/ImagesListFolder/ImagesListViewController.swift
> +    }
Александра, добрый день!  Спасибо за важное уточнение! Со статьей ознакомился, однако некоторые моменты пока что прошли "мимо меня" так как специфику загруженности и "дороговизны" кода я наверно во всей красе пойму на реальных проектах(

В итоге решил пойти по пути Первого проекта -> вынес форматтер в отдельный файл + добился удаления "г." после даты в целях  единообразия проекта и макета.

2023-05-25 14:09 UTC, DanteIT94 commented on pinterestClone/ImagesListFolder/ImagesListViewController.swift
> +                self.showAlertViewController()
Так, почитал статьи и немного разобрался -> мы в первую очередь очередь на главный поток пускаем UI-логику чтобы пользователю все отображалось все корректно

По такой логике действительно и case .failure должен обрабатываться в main

2023-05-25 14:09 UTC, DanteIT94 commented on pinterestClone/ImagesListFolder/ImagesListService.swift
> +
Понял, исправлюсь!

2023-05-25 14:10 UTC, DanteIT94 commented on pinterestClone/ImagesListFolder/ImagesListService.swift
> +                return
Когда писал эту часть кода, видимо разум уже затуманился а потому просто пропускал его

2023-05-25 15:19 UTC, DanteIT94 commented on pinterestClone/UserProfileFolder/ProfileViewController.swift
> +        tokenStorage.keychainWrapper.removeObject(forKey: "token")
Действительно, видимо я просто не привык работать еще кейчейнами - просто напрямую вызвал KeychainWrapper.standart в методе чтобы не скрещиваться с storage)
Спасибо за наглядное выделение архитектурных ошибок! С каждым днем буду становиться лучше)

2023-05-25 15:20 UTC, DanteIT94 commented on pinterestClone/ImagesListFolder/ImagesListViewController.swift
> +                guard let self else {return}
Ок

2023-05-25 15:20 UTC, DanteIT94 commented on pinterestClone/ImagesListFolder/ImagesListService.swift
> +        let dataTask = urlSession.objectTask(for: request) {[weak self] (result: Result<[PhotoResult],Error>) in
Ок

2023-05-26 18:56 UTC, IBDesignable approved these changes

2023-05-26 18:56 UTC, IBDesignable commented on pinterestClone/UserProfileFolder/Models/ProfileResultModel.swift
> +        case bio = "bio"
CodingKeys – это один из вариантов решения задачи. Также можно настроить JsonDecoder таким образом, чтобы он данные сам преобразовывал из snake_case до camelCase

https://nemecek.be/blog/90/how-to-decode-snake-case-with-codable  - можно подробнее тут

2023-05-26 18:56 UTC, IBDesignable commented on pinterestClone/UserProfileFolder/ProfileViewController.swift
> +            guard let self = self else {return}
```suggestion
            guard let self = self else { return }
```

2023-05-26 18:56 UTC, IBDesignable commented on pinterestClone/UserProfileFolder/ProfileViewController.swift
> +        KeychainWrapper.standard.removeObject(forKey: "token")
Может в прошлый раз выразилась некорректно, но в предыдущей версии был TokenStorage, который работал сначала с UserDefaults, так и почему бы им дальше и не пользоваться: нужно прятать внешние зависимости, оборачивая их в интерфейс на языке приложения.
например `resetToken`.

2023-05-26 18:56 UTC, IBDesignable commented on pinterestClone/UserProfileFolder/ProfileViewController.swift
> +    private func setAvatarGradient() {
круто что сделал анимацию 👍🏻

2023-05-26 18:56 UTC, IBDesignable commented on pinterestClone/ImagesListFolder/SingleImageFolder/SingleImageViewController.swift
> +        present(alertVC, animated: true)
Задача-челендж: написать AlertPresenter, аналогичный тому из MovieQuiz, чтобы работать с ним в этом приложении

2023-05-26 18:56 UTC, IBDesignable commented on pinterestClone/ImagesListFolder/SingleImageFolder/SingleImageViewController.swift
> +            case .failure(_):
Можно упростить
```suggestion
            case .failure:
```

2023-05-26 18:56 UTC, IBDesignable commented on pinterestClone/ImagesListFolder/SingleImageFolder/SingleImageViewController.swift
> +                self.rescaleAndCenterImageInScrollView(image: ResultImage.image)
последи за camelCase в своем коде:
```suggestion
            case .success(let resultImage):
                createSingleImageView()
                self.rescaleAndCenterImageInScrollView(image: resultImage.image)
```

2023-05-26 18:56 UTC, IBDesignable commented on pinterestClone/ImagesListFolder/SingleImageFolder/SingleImageViewController.swift
> +        guard let fullImageUrl = fullImageUrl else {return}
и еще разок :)
```suggestion
        guard let fullImageUrl = fullImageUrl else { return }
```

2023-05-26 18:56 UTC, IBDesignable commented on pinterestClone/ImagesListFolder/SingleImageFolder/SingleImageViewController.swift
> +        imageView.kf.setImage(with: fullImageUrl) {[weak self] result in
```suggestion
        imageView.kf.setImage(with: fullImageUrl) { [weak self] result in
```

2023-05-26 18:56 UTC, IBDesignable commented on pinterestClone/ImagesListFolder/ImagesListViewController.swift
> +    ///В этом методе вызываем метод fetchPhotosNextPage из ImagesListService
после док-коммента пробел оставляют:
```suggestion
    /// В этом методе вызываем метод fetchPhotosNextPage из ImagesListService
```

2023-05-26 18:56 UTC, IBDesignable commented on pinterestClone/Helpers/Date+Extension .swift
> +}
давай отступ поправим : control + i

2023-05-26 19:55 UTC, DanteIT94 commented on pinterestClone/UserProfileFolder/ProfileViewController.swift
> +        KeychainWrapper.standard.removeObject(forKey: "token")
Ааа, понял! Прячем внешние зависимости, чтобы в случае их "упразднения" можно было бы только в одном месте отредактировать код! Исправлю!

2023-05-26 19:59 UTC, DanteIT94 commented on pinterestClone/UserProfileFolder/ProfileViewController.swift
> +    private func setAvatarGradient() {
Дальше - Больше!!

2023-05-26 19:59 UTC, DanteIT94 commented on pinterestClone/ImagesListFolder/SingleImageFolder/SingleImageViewController.swift
> +        present(alertVC, animated: true)
Челендж принят!

2023-05-26 20:05 UTC, DanteIT94 commented on pinterestClone/UserProfileFolder/Models/ProfileResultModel.swift
> +        case bio = "bio"
Ого! Даже не знал о таком функционале - попробую имплементировать!

2023-05-27 11:04 UTC, DanteIT94 commented on pinterestClone/UserProfileFolder/ProfileViewController.swift
> +        KeychainWrapper.standard.removeObject(forKey: "token")
Готово!

2023-05-27 17:31 UTC, merged